name: Asset Generation
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1
      - uses: "./.github/actions/inkscape"
        with:
          run: |
            find designs -name "*.svg" -exec export {} \;
      - run: |
          cd designs; zip -r9 ../stickers.zip .
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          path: stickers.zip
          retention-days: 1
      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: stickers.zip
